# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Мероприятия'},
        ),
    ]
