# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 22:16
from __future__ import unicode_literals

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='default/album_avatar.jpg', upload_to=albums.models.album_cover_path),
        ),
    ]
