# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20180406_1256'),
        ('albums', '0002_auto_20180407_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
    ]
