# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tournament',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
        ),
    ]
