# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20180407_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
