# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_auto_20180408_0204'),
        ('albums', '0005_auto_20180407_1727'),
    ]

    operations = [
    ]
