# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 16:52
from __future__ import unicode_literals

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_merge_20180413_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='default/album_avatar.jpg', upload_to=albums.models.album_cover_path),
        ),
    ]
