# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_auto_20180424_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tournament',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_album', to='tournaments.Tournament'),
        ),
    ]
