# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 12:10
from __future__ import unicode_literals

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0009_auto_20180513_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='default\\album_avatar.jpg', upload_to=albums.models.album_cover_path),
        ),
    ]
