# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0014_auto_20180424_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('tournaments', models.ManyToManyField(to='tournaments.Tournament')),
            ],
        ),
    ]
