# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20180424_1952'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='type',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='tournaments.TournamentType'),
            preserve_default=False,
        ),
    ]
