# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rating_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name_plural': 'Рейтинги'},
        ),
    ]
