# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import tournaments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('description', models.TextField(max_length=500, null=True)),
                ('type', models.CharField(choices=[(0, 'Public'), (1, 'Club license'), (2, 'Private license')], default=0, max_length=1)),
                ('team_type', models.CharField(choices=[(0, 'Solo'), (1, 'Dual')], default=0, max_length=1)),
                ('photo', models.ImageField(blank=True, upload_to=tournaments.models.filename)),
            ],
        ),
    ]
