# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('Только для обладателей клубной лицензии', 'CLUB LICENSE'), ('Только для обладателей игровой лицензии', 'GAME LICENSE'), ('Для обладателей любой лицензии', 'ANY LICENSE'), ('Публичный', 'PUBLIC')], max_length=1),
        ),
    ]
