# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20180129_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('0', 'Public'), ('1', 'Club license'), ('2', 'Private license'), ('3', 'Any license')], max_length=1),
        ),
    ]
