# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20180221_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('C', 'Только для обладателей клубной лицензии'), ('G', 'Только для обладателей игровой лицензии'), ('L', 'Для обладателей любой лицензии'), ('P', 'Публичный')], max_length=1),
        ),
    ]
