# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_auto_20180201_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='team_type',
            field=models.CharField(choices=[('0', 'Один игрок'), ('1', 'Два игрока')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('0', 'Публичный'), ('1', 'Только для обладателей клубной лицензии'), ('2', 'Только для обладателей членской лицензии'), ('3', 'Для обладателей любой лицензии')], max_length=1),
        ),
    ]
