# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 11:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20180312_2125'),
        ('tournaments', '0004_auto_20180312_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.ForeignKey(default=7264, on_delete=django.db.models.deletion.CASCADE, to='accounts.City'),
        ),
    ]
