# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('tournaments', '0004_auto_20180201_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(to='Auth.PlayerInfo'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('0', 'Публичный'), ('1', 'Только для обладателей клубной лицензии'), ('2', 'Только для обладателей игровой лицензии'), ('3', 'Для обладателей любой лицензии')], max_length=1),
        ),
    ]
