# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0004_auto_20180221_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
