# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tournaments.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, default='default\\tournament_avatar.png', upload_to=tournaments.models.filename),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.TournamentType'),
        ),
    ]
