# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models

import tournaments.models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0006_auto_20180322_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, default='default/tournament_avatar.png',
                                    upload_to=tournaments.models.filename),
        ),
    ]
