# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 06:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0007_auto_20180406_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.TournamentType'),
        ),
    ]
