# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0008_auto_20180406_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='games',
        ),
    ]
