# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 09:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0009_remove_tournament_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.ForeignKey(default=5139, on_delete=django.db.models.deletion.CASCADE, to='accounts.City'),
        ),
    ]
