# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import tournaments.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_auto_20180406_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='photo',
            field=models.ImageField(blank=True, default='default\\tournament_avatar.png', upload_to=tournaments.models.filename),
        ),
    ]
