# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_auto_20180424_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='teamtype',
            options={'verbose_name_plural': 'Типы команд'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
