# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180920_1510'),
        ('tournaments', '0015_auto_20180921_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PlayerInfo')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='tournament_players', through='tournaments.TournamentMembership', to='accounts.PlayerInfo'),
        ),
    ]
