# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_auto_20180921_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
    ]
