# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180920_1510'),
        ('tournaments', '0017_remove_team_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='team_players', to='accounts.PlayerInfo'),
        ),
    ]
