# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_team_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
