# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_team_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='type',
        ),
        migrations.AddField(
            model_name='tournament',
            name='block_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='block_type', to='tournaments.BlockType'),
            preserve_default=False,
        ),
    ]
