# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180920_1510'),
        ('tournaments', '0020_auto_20180924_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='players',
            field=models.ManyToManyField(related_name='block', to='accounts.PlayerInfo'),
        ),
        migrations.AlterField(
            model_name='game',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tournaments.Block'),
        ),
    ]
