# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_auto_20180930_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.ManyToManyField(related_name='game', to='tournaments.GameInfo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='team', to='accounts.PlayerInfo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.Tournament'),
        ),
    ]
