# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180920_1510'),
        ('tournaments', '0022_auto_20181008_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='team',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='accounts.PlayerInfo'),
            preserve_default=False,
        ),
    ]
