# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_auto_20181014_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.TeamType'),
            preserve_default=False,
        ),
    ]
