# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0024_team_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='info',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='player',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='tournaments.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='tournaments.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='tournaments.Tournament'),
        ),
    ]
