# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0025_auto_20181104_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_info', to='tournaments.Game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_info', to='tournaments.Team')),
            ],
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='team_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_infos', to='tournaments.TeamGameInfo'),
        ),
    ]
