# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181107_2000'),
        ('tournaments', '0026_auto_20181107_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='team_info',
        ),
        migrations.AddField(
            model_name='teamgameinfo',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='in_team_info', to='accounts.PlayerInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamgameinfo',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamgameinfo',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_info', to='tournaments.Team'),
        ),
    ]
