# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0027_auto_20181115_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('gender', models.CharField(choices=[('0', 'Женский'), ('1', 'Мужской')], default='0', max_length=1)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_Handicap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.Handicap')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='handicap',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='handicap_size',
        ),
        migrations.AddField(
            model_name='tournament_handicap',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handicaps', to='tournaments.Tournament'),
        ),
    ]
