# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-18 16:24
from __future__ import unicode_literals

from django.db import migrations, models

import accounts.utils


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='avatar',
            field=models.ImageField(default='123', upload_to=accounts.utils.UploadToPathAndRename('avatars/')),
            preserve_default=False,
        ),
    ]
