# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 19:46
from __future__ import unicode_literals

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180210_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerinfo',
            old_name='last_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='playerinfo',
            old_name='first_name',
            new_name='i_name',
        ),
        migrations.RemoveField(
            model_name='playerinfo',
            name='patronymic',
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='o_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='city',
            field=models.CharField(blank=True, default='Не указан', max_length=30),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='license',
            field=models.CharField(blank=True, default='Не указана', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='passport',
            field=models.ImageField(upload_to=accounts.utils.filename),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='phone',
            field=models.CharField(blank=True, default='Не указан', max_length=15),
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='sex',
            field=models.CharField(choices=[('0', 'Мужской'), ('1', 'Женский')], default='0', max_length=1),
        ),
    ]
