# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_playerinfo_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Не указан', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='playerinfo',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.City'),
        ),
    ]
