# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-22 18:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20180222_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.City'),
        ),
    ]
