# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models

import accounts.utils


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20180322_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='avatar',
            field=models.ImageField(default='default/player_avatar.png',
                                    upload_to=accounts.utils.UploadToPathAndRename('avatars/')),
        ),
    ]
