# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0004_auto_20180406_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_photographer',
            field=models.BooleanField(default=False),
        ),
    ]
