# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_is_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='playerinfo',
            options={'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='sportcategory',
            options={'verbose_name_plural': 'Спортивные разряды'},
        ),
        migrations.RemoveField(
            model_name='playerinfo',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='playerinfo',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='playerinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='email',
            field=models.EmailField(default='empty@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
    ]
