# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181016_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
