# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowling_app', '0002_auto_20180316_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
