# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20180127_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='passport',
            field=models.ImageField(blank=True, upload_to='test\\filename'),
        ),
    ]
