# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20180124_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[(0, 'Мужской'), (1, 'Женский')], max_length=1, null=True),
        ),
    ]
