# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 13:32
from __future__ import unicode_literals

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20180127_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinfo',
            name='passport',
            field=models.ImageField(blank=True, upload_to=Auth.models.user_folder),
        ),
    ]
