# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='status',
            field=models.CharField(choices=[(0, 'In progress'), (1, 'Accepted'), (2, 'Declined')], default=0, max_length=1),
        ),
    ]
